/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as ViewspecRouteImport } from './routes/viewspec'
import { Route as WidgetIdRouteImport } from './routes/widget.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewspecRoute = ViewspecRouteImport.update({
  id: '/viewspec',
  path: '/viewspec',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIdRoute = WidgetIdRouteImport.update({
  id: '/widget/$id',
  path: '/widget/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/viewspec': typeof ViewspecRoute
  '/widget/$id': typeof WidgetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/viewspec': typeof ViewspecRoute
  '/widget/$id': typeof WidgetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/viewspec': typeof ViewspecRoute
  '/widget/$id': typeof WidgetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/viewspec' | '/widget/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/viewspec' | '/widget/$id'
  id: '__root__' | '/' | '/new' | '/viewspec' | '/widget/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ViewspecRoute: typeof ViewspecRoute
  WidgetIdRoute: typeof WidgetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewspec': {
      id: '/viewspec'
      path: '/viewspec'
      fullPath: '/viewspec'
      preLoaderRoute: typeof ViewspecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$id': {
      id: '/widget/$id'
      path: '/widget/$id'
      fullPath: '/widget/$id'
      preLoaderRoute: typeof WidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ViewspecRoute: ViewspecRoute,
  WidgetIdRoute: WidgetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
